### ISSUE TITLE
Error - Option: -autotune-email is mandatory but no option set.

### ISSUE THREAD

**Issue by schabacker** [gh-davidr/UnattendedAutotuneWeb#1]
My email address was entered as instructed. I get this error when I try to run UnattendedAutotuneweb.bat

![UnattendedAutotune screenshot](https://user-images.githubusercontent.com/52434928/63630286-b5803280-c5de-11e9-81c5-8bc2a400ae13.PNG)

**Comment by gh-davidr** [comment]
Application works as expected - there is no issue.

To work correctly, pass email address after -autotune-email parameter.
